
### Create Service By Name
POST http://127.0.0.1:8088/k8sailor/v0/services/demo-nginx-cluster1-2?namespace=default
Content-Type: application/json

{
    "ports":[
        "80:8080",
        "81:8080"
    ]
}

